// SCIM 2.0 user provisioning and deprovisioning (RFC 7643 / RFC 7644) for an organization's
// identity provider (Microsoft Entra ID, Okta, OneLogin, JumpCloud…).
//
// Tokens: per organization, generated by an admin, shown once; only a SHA-256 is stored (like API
// keys). A token acts only on its own organization: every query below is scoped by the token's
// org_id, and a user id from another organization is simply "not found".
//
// Users: the SCIM User's userName is the member's email (Planora's sign-in identity). New members
// get an unusable random password and sign in through SSO. Their email must be in one of the
// organization's verified SSO domains, so a token cannot create accounts for arbitrary addresses.
// Roles come from the User's "roles" attribute (admin, scheduler, reviewer, viewer; never owner),
// else the SSO default role. Owners are managed in Planora: SCIM cannot deactivate them or change
// their role or email.
//
// Deprovisioning (active=false, or DELETE) disables the account and revokes all of its sessions in
// the same transaction, so access ends on the next request. DELETE also hides the user from SCIM
// (a later GET is 404); the firm keeps its project data, as with removing a member by hand.
// Every change is in the audit log under the token's name.

import { randomUUID } from 'crypto'
import { initSchema, query, withTransaction } from '@/lib/db'
import { ScimError } from './api'
import { audit } from './audit'
import { randomToken, sha256 } from './crypto'
import { isRole, type Role } from './permissions'
import { hashPassword } from '@/lib/auth'

/* ─── Tokens ────────────────────────────────────────── */

export const SCIM_TOKEN_PREFIX = 'scim_'
export const MAX_SCIM_TOKENS = 10

export interface ScimToken { id: string; name: string; prefix: string; createdBy: string; createdAt: string; lastUsedAt: string | null; revokedAt: string | null }

const iso = (v: unknown) => (v ? new Date(v as string).toISOString() : null)
const rowToToken = (r: Record<string, unknown>): ScimToken => ({
  id: String(r.id), name: String(r.name), prefix: String(r.prefix), createdBy: String(r.created_by),
  createdAt: iso(r.created_at)!, lastUsedAt: iso(r.last_used_at), revokedAt: iso(r.revoked_at),
})

export const looksLikeScimToken = (s: string) => /^scim_[A-Za-z0-9_-]{40,60}$/.test(s)

export async function createScimToken(orgId: string, input: { name: string; createdBy: string }): Promise<{ token: ScimToken; secret: string }> {
  await initSchema()
  const secret = SCIM_TOKEN_PREFIX + randomToken(32)
  const res = await query('INSERT INTO scim_tokens (id, org_id, name, prefix, token_hash, created_by) VALUES ($1,$2,$3,$4,$5,$6) RETURNING *',
    [randomUUID(), orgId, input.name, secret.slice(0, SCIM_TOKEN_PREFIX.length + 6), sha256(secret), input.createdBy])
  return { token: rowToToken(res.rows[0]), secret }
}

export async function listScimTokens(orgId: string): Promise<ScimToken[]> {
  await initSchema()
  const res = await query('SELECT * FROM scim_tokens WHERE org_id=$1 ORDER BY revoked_at IS NOT NULL, created_at DESC', [orgId])
  return res.rows.map(rowToToken)
}

export async function countActiveScimTokens(orgId: string): Promise<number> {
  await initSchema()
  const res = await query('SELECT COUNT(*)::int AS n FROM scim_tokens WHERE org_id=$1 AND revoked_at IS NULL', [orgId])
  return Number(res.rows[0]?.n || 0)
}

export async function revokeScimToken(orgId: string, id: string): Promise<ScimToken | null> {
  await initSchema()
  const res = await query('UPDATE scim_tokens SET revoked_at=NOW() WHERE id=$1 AND org_id=$2 AND revoked_at IS NULL RETURNING *', [id, orgId])
  return res.rows[0] ? rowToToken(res.rows[0]) : null
}

export async function resolveScimToken(secret: string): Promise<{ orgId: string; tokenId: string; tokenName: string; plan: string } | null> {
  if (!looksLikeScimToken(secret)) return null
  await initSchema()
  const res = await query(`SELECT t.id, t.org_id, t.name, t.last_used_at, o.plan FROM scim_tokens t JOIN organizations o ON o.id=t.org_id
    WHERE t.token_hash=$1 AND t.revoked_at IS NULL`, [sha256(secret)])
  const r = res.rows[0]
  if (!r) return null
  if (!r.last_used_at || Date.now() - new Date(r.last_used_at).getTime() > 60_000) await query('UPDATE scim_tokens SET last_used_at=NOW() WHERE id=$1', [r.id])
  return { orgId: String(r.org_id), tokenId: String(r.id), tokenName: String(r.name), plan: String(r.plan || 'free') }
}

/* ─── Resource shapes (RFC 7643) ────────────────────── */

export const SCHEMA = {
  user: 'urn:ietf:params:scim:schemas:core:2.0:User',
  list: 'urn:ietf:params:scim:api:messages:2.0:ListResponse',
  patch: 'urn:ietf:params:scim:api:messages:2.0:PatchOp',
  spc: 'urn:ietf:params:scim:schemas:core:2.0:ServiceProviderConfig',
  resourceType: 'urn:ietf:params:scim:schemas:core:2.0:ResourceType',
  schema: 'urn:ietf:params:scim:schemas:core:2.0:Schema',
} as const

export const scimBase = (origin: string) => `${origin.replace(/\/$/, '')}/api/scim/v2`

type Row = Record<string, unknown>

function splitName(name: string): { givenName: string; familyName: string } {
  const parts = name.trim().split(/\s+/)
  return { givenName: parts[0] || '', familyName: parts.slice(1).join(' ') }
}

export function toScimUser(r: Row, origin: string) {
  const name = String(r.name || '')
  const created = iso(r.created_at)!
  return {
    schemas: [SCHEMA.user],
    id: String(r.id),
    ...(r.scim_external_id ? { externalId: String(r.scim_external_id) } : {}),
    userName: String(r.email),
    name: { formatted: name, ...splitName(name) },
    displayName: name,
    emails: [{ value: String(r.email), type: 'work', primary: true }],
    active: !r.disabled_at,
    roles: [{ value: String(r.role || 'viewer'), primary: true }],
    meta: { resourceType: 'User', created, lastModified: iso(r.scim_modified_at) || created, location: `${scimBase(origin)}/Users/${r.id}` },
  }
}

export function listResponse(resources: unknown[], total: number, startIndex: number) {
  return { schemas: [SCHEMA.list], totalResults: total, startIndex, itemsPerPage: resources.length, Resources: resources }
}

/* ─── Filtering and paging (RFC 7644 §3.4.2) ────────── */

const FILTER_COLUMNS: Record<string, string> = {
  username: 'LOWER(email)', 'emails.value': 'LOWER(email)', emails: 'LOWER(email)', 'emails[type eq "work"].value': 'LOWER(email)',
  externalid: 'scim_external_id', id: 'id',
}

/** Supports `<attr> eq "<value>"` for userName, emails.value, externalId and id (what IdPs use to match users). */
export function parseFilter(filter: string | null): { column: string; value: string } | null {
  if (filter == null || filter.trim() === '') return null
  if (filter.length > 512) throw new ScimError(400, 'Filter too long.', 'invalidFilter')
  const m = /^\s*([A-Za-z0-9:._-]+?(?:\[type eq "work"\]\.value)?)\s+eq\s+"((?:[^"\\]|\\.)*)"\s*$/i.exec(filter)
  if (!m) throw new ScimError(400, 'Only filters of the form userName eq "value" (also emails.value, externalId, id) are supported.', 'invalidFilter')
  const attr = m[1].replace(/^urn:ietf:params:scim:schemas:core:2\.0:User:/i, '')
  const key = attr.toLowerCase() === 'emails[type eq "work"].value' ? 'emails[type eq "work"].value' : attr.toLowerCase()
  const column = FILTER_COLUMNS[key]
  if (!column) throw new ScimError(400, `Filtering on ${attr} is not supported.`, 'invalidFilter')
  let value = m[2].replace(/\\(.)/g, '$1')
  if (column === 'LOWER(email)') value = value.toLowerCase()
  return { column, value }
}

export function paging(params: URLSearchParams): { startIndex: number; count: number } {
  const si = Number.parseInt(params.get('startIndex') || '1', 10)
  const c = Number.parseInt(params.get('count') || '100', 10)
  return { startIndex: Number.isFinite(si) && si >= 1 ? si : 1, count: Number.isFinite(c) ? Math.min(Math.max(c, 0), 200) : 100 }
}

/* ─── Users ─────────────────────────────────────────── */

const LIVE = 'org_id=$1 AND scim_deleted_at IS NULL'

export async function listScimUsers(orgId: string, filter: { column: string; value: string } | null, startIndex: number, count: number): Promise<{ rows: Row[]; total: number }> {
  await initSchema()
  const where = filter ? `${LIVE} AND ${filter.column}=$2` : LIVE
  const params: unknown[] = filter ? [orgId, filter.value] : [orgId]
  const total = Number((await query(`SELECT COUNT(*)::int AS n FROM users WHERE ${where}`, params)).rows[0]?.n || 0)
  if (count === 0) return { rows: [], total }
  const n = params.length
  const res = await query(`SELECT * FROM users WHERE ${where} ORDER BY created_at, id LIMIT $${n + 1} OFFSET $${n + 2}`, [...params, count, startIndex - 1])
  return { rows: res.rows, total }
}

export async function getScimUser(orgId: string, id: string): Promise<Row> {
  await initSchema()
  const res = await query(`SELECT * FROM users WHERE ${LIVE} AND id=$2`, [orgId, id])
  if (!res.rows[0]) throw new ScimError(404, 'User not found.')
  return res.rows[0]
}

/** What a SCIM request wants a member to look like (absent = unchanged). */
export interface Desired {
  email?: string; name?: string; givenName?: string; familyName?: string; externalId?: string | null; active?: boolean; role?: Role | null
}

const bool = (v: unknown): boolean => {
  if (typeof v === 'boolean') return v
  if (typeof v === 'string' && /^(true|false)$/i.test(v.trim())) return v.trim().toLowerCase() === 'true'
  throw new ScimError(400, '"active" must be true or false.', 'invalidValue')
}
const scimStr = (v: unknown, what: string, max = 320): string => {
  if (typeof v !== 'string') throw new ScimError(400, `${what} must be a string.`, 'invalidValue')
  return v.trim().slice(0, max)
}

function roleFrom(v: unknown): Role | null {
  const list = Array.isArray(v) ? v : v == null ? [] : [v]
  if (!list.length) return null
  const pick = (list.find(x => x && typeof x === 'object' && (x as Row).primary === true) ?? list[0]) as unknown
  const raw = typeof pick === 'string' ? pick : pick && typeof pick === 'object' ? (pick as Row).value ?? (pick as Row).display : undefined
  const role = typeof raw === 'string' ? raw.trim().toLowerCase() : ''
  if (!isRole(role)) throw new ScimError(400, `Unknown role "${String(raw)}". Use admin, scheduler, reviewer or viewer.`, 'invalidValue')
  if (role === 'owner') throw new ScimError(400, 'The owner role cannot be assigned through SCIM.', 'invalidValue')
  return role
}

function emailFrom(emails: unknown): string | undefined {
  if (!Array.isArray(emails) || !emails.length) return undefined
  const e = (emails.find(x => x && typeof x === 'object' && (x as Row).primary === true) ?? emails.find(x => x && typeof x === 'object' && (x as Row).type === 'work') ?? emails[0]) as Row
  return e && typeof e.value === 'string' ? e.value.trim().toLowerCase() : undefined
}

function applyNameObject(d: Desired, v: unknown) {
  if (!v || typeof v !== 'object') return
  const n = v as Row
  if (typeof n.formatted === 'string' && n.formatted.trim()) d.name = n.formatted.trim()
  if (typeof n.givenName === 'string') d.givenName = n.givenName.trim()
  if (typeof n.familyName === 'string') d.familyName = n.familyName.trim()
}

/** A full User resource (POST / PUT). PUT replaces: active defaults to true; an absent role keeps the current one. */
export function desiredFromResource(b: Row): Desired {
  const schemas = Array.isArray(b.schemas) ? b.schemas.map(String) : []
  if (!schemas.includes(SCHEMA.user)) throw new ScimError(400, `The resource must list the schema ${SCHEMA.user}.`, 'invalidSyntax')
  if (typeof b.userName !== 'string' || !b.userName.trim()) throw new ScimError(400, 'userName is required.', 'invalidValue')
  const d: Desired = {
    email: (emailFrom(b.emails) && !b.userName.includes('@') ? emailFrom(b.emails)! : b.userName.trim().toLowerCase()),
    externalId: typeof b.externalId === 'string' ? b.externalId.trim().slice(0, 255) || null : null,
    active: b.active === undefined ? true : bool(b.active),
    role: b.roles === undefined ? undefined : roleFrom(b.roles),
  }
  applyNameObject(d, b.name)
  if (!d.name && !d.givenName && typeof b.displayName === 'string') d.name = b.displayName.trim()
  return d
}

const PATH_PREFIX = /^urn:ietf:params:scim:schemas:core:2\.0:User:/i

/** Applies RFC 7644 §3.5.2 PATCH operations to a Desired change set. Unknown attributes are ignored. */
export function desiredFromPatch(b: Row): Desired {
  const schemas = Array.isArray(b.schemas) ? b.schemas.map(String) : []
  if (!schemas.includes(SCHEMA.patch)) throw new ScimError(400, `PATCH requests must list the schema ${SCHEMA.patch}.`, 'invalidSyntax')
  const ops = b.Operations
  if (!Array.isArray(ops) || !ops.length || ops.length > 100) throw new ScimError(400, 'Operations must be a non-empty array.', 'invalidSyntax')
  const d: Desired = {}
  const set = (path: string, value: unknown, op: string) => {
    const p = path.replace(PATH_PREFIX, '').trim()
    const key = p.toLowerCase()
    const remove = op === 'remove'
    switch (key) {
      case 'active': if (!remove) d.active = bool(value); break
      case 'username': if (!remove) d.email = scimStr(value, 'userName').toLowerCase(); break
      case 'emails': if (!remove) { const e = emailFrom(Array.isArray(value) ? value : [value]); if (e) d.email = e } break
      case 'emails[type eq "work"].value': case 'emails.value': if (!remove) d.email = scimStr(value, 'email').toLowerCase(); break
      case 'displayname': case 'name.formatted': if (!remove) d.name = scimStr(value, 'name', 120); break
      case 'name': if (!remove) applyNameObject(d, value); break
      case 'name.givenname': d.givenName = remove ? '' : scimStr(value, 'givenName', 120); break
      case 'name.familyname': d.familyName = remove ? '' : scimStr(value, 'familyName', 120); break
      case 'externalid': d.externalId = remove ? null : scimStr(value, 'externalId', 255) || null; break
      case 'roles': d.role = remove ? null : roleFrom(value); break
      default:
        if (/^roles\[.*\]\.value$/.test(key) && !remove) d.role = roleFrom(value)
        // Other attributes (title, phone numbers, enterprise extension…) are not stored; ignore them.
    }
  }
  for (const raw of ops) {
    const o = (raw && typeof raw === 'object' ? raw : {}) as Row
    const op = String(o.op || '').toLowerCase()
    if (!['add', 'replace', 'remove'].includes(op)) throw new ScimError(400, `Unsupported PATCH op "${String(o.op)}".`, 'invalidSyntax')
    if (typeof o.path === 'string' && o.path.trim()) set(o.path, o.value, op)
    else if (op === 'remove') throw new ScimError(400, 'remove requires a path.', 'noTarget')
    else if (o.value && typeof o.value === 'object' && !Array.isArray(o.value)) for (const [k, v] of Object.entries(o.value as Row)) set(k, v, op)
    else throw new ScimError(400, 'A PATCH operation without a path needs an object value.', 'invalidSyntax')
  }
  return d
}

const EMAIL_RE = /^[^@\s]+@[^@\s]+\.[^@\s]+$/

async function verifiedDomains(orgId: string): Promise<string[]> {
  const res = await query('SELECT domain FROM sso_domains WHERE org_id=$1 UNION SELECT domain FROM saml_domains WHERE org_id=$1', [orgId])
  return res.rows.map(r => String(r.domain))
}

async function checkEmail(orgId: string, email: string) {
  if (!EMAIL_RE.test(email) || email.length > 254) throw new ScimError(400, 'userName must be the member\'s email address.', 'invalidValue')
  const domains = await verifiedDomains(orgId)
  if (!domains.includes(email.split('@')[1])) {
    throw new ScimError(400, `${email.split('@')[1]} is not one of this organization's verified single sign-on domains (${domains.join(', ') || 'none yet'}).`, 'invalidValue')
  }
}

async function defaultRole(orgId: string): Promise<Role> {
  const res = await query('SELECT sso, saml FROM organizations WHERE id=$1', [orgId])
  const r = res.rows[0] || {}
  const pick = (c: unknown) => { const v = (c && typeof c === 'object' ? (c as Row).defaultRole : undefined); return isRole(v) && v !== 'owner' ? v : null }
  const saml = r.saml && typeof r.saml === 'object' && (r.saml as Row).enabled ? pick(r.saml) : null
  return saml || pick(r.sso) || 'viewer'
}

function composeName(cur: string, d: Desired, email: string): string {
  if (d.name) return d.name.slice(0, 120)
  if (d.givenName !== undefined || d.familyName !== undefined) {
    const cs = splitName(cur)
    const n = [d.givenName ?? cs.givenName, d.familyName ?? cs.familyName].filter(Boolean).join(' ').trim()
    if (n) return n.slice(0, 120)
  }
  return cur || email.split('@')[0]
}

/** Disables the member and revokes every session in one transaction. Returns how many sessions ended. */
async function deactivate(orgId: string, userId: string, markDeleted: boolean): Promise<number> {
  return withTransaction(async q => {
    await q(`UPDATE users SET disabled_at=COALESCE(disabled_at, NOW()), scim_modified_at=NOW()${markDeleted ? ', scim_deleted_at=NOW()' : ''} WHERE id=$1 AND org_id=$2`, [userId, orgId])
    const s = await q('UPDATE sessions SET revoked_at=NOW() WHERE user_id=$1 AND revoked_at IS NULL', [userId])
    return s.rowCount ?? 0
  })
}

export async function createScimUser(orgId: string, b: Row): Promise<{ row: Row; created: boolean }> {
  await initSchema()
  const d = desiredFromResource(b)
  const email = d.email!
  await checkEmail(orgId, email)
  const existing = (await query('SELECT * FROM users WHERE LOWER(email)=LOWER($1)', [email])).rows[0]
  if (existing && existing.org_id !== orgId) throw new ScimError(409, 'That userName is not available.', 'uniqueness')
  if (existing && !existing.scim_deleted_at) throw new ScimError(409, 'A user with this userName already exists.', 'uniqueness')
  const role = d.role || await defaultRole(orgId)
  const name = composeName('', d, email)
  let row: Row
  if (existing) {
    // Re-provisioning someone who was deleted through SCIM: same account, so their history stays linked.
    if (existing.role === 'owner') throw new ScimError(400, 'Owners are managed in Planora, not through SCIM.', 'mutability')
    row = (await query(`UPDATE users SET name=$3, role=$4, scim_external_id=$5, disabled_at=${d.active === false ? 'NOW()' : 'NULL'}, scim_deleted_at=NULL, scim_modified_at=NOW(), failed_logins=0, locked_until=NULL
      WHERE id=$1 AND org_id=$2 RETURNING *`, [existing.id, orgId, name, role, d.externalId ?? null])).rows[0]
  } else {
    row = (await query(`INSERT INTO users (id, email, name, password_hash, plan, created_at, org_id, role, password_changed_at, email_verified_at, scim_external_id, scim_modified_at, disabled_at)
      VALUES ($1,$2,$3,$4,'free',NOW(),$5,$6,NOW(),NOW(),$7,NOW(),${d.active === false ? 'NOW()' : 'NULL'}) RETURNING *`,
      [randomUUID(), email, name, await hashPassword(randomToken(32)), orgId, role, d.externalId ?? null])).rows[0]
  }
  await audit({ orgId, action: 'scim.user_created', targetType: 'user', targetId: String(row.id), detail: { email, role, active: !row.disabled_at, reprovisioned: !!existing } })
  return { row, created: !existing }
}

/** Applies a change set (PUT or PATCH) with the owner and uniqueness rules, deprovisioning on active=false. */
export async function updateScimUser(orgId: string, id: string, d: Desired): Promise<Row> {
  const cur = await getScimUser(orgId, id)
  const curEmail = String(cur.email).toLowerCase()
  const email = d.email ?? curEmail
  const role: Role = d.role === undefined ? (cur.role as Role) : d.role ?? (cur.role === 'owner' ? 'owner' : await defaultRole(orgId))
  const active = d.active ?? !cur.disabled_at
  const owner = cur.role === 'owner'
  if (owner && (!active || role !== 'owner' || email !== curEmail)) throw new ScimError(400, 'Owners are managed in Planora: SCIM cannot deactivate them or change their role or email.', 'mutability')
  if (email !== curEmail) {
    await checkEmail(orgId, email)
    const taken = await query('SELECT id FROM users WHERE LOWER(email)=LOWER($1) AND id<>$2', [email, id])
    if (taken.rows.length) throw new ScimError(409, 'That userName is not available.', 'uniqueness')
  }
  const name = composeName(String(cur.name || ''), d, email)
  const externalId = d.externalId === undefined ? (cur.scim_external_id as string | null) ?? null : d.externalId
  const changes: Record<string, { before: unknown; after: unknown }> = {}
  if (email !== curEmail) changes.email = { before: curEmail, after: email }
  if (name !== cur.name) changes.name = { before: cur.name, after: name }
  if (role !== cur.role) changes.role = { before: cur.role, after: role }
  if (externalId !== (cur.scim_external_id ?? null)) changes.externalId = { before: cur.scim_external_id ?? null, after: externalId }
  if (Object.keys(changes).length) {
    await query('UPDATE users SET email=$3, name=$4, role=$5, scim_external_id=$6, scim_modified_at=NOW() WHERE id=$1 AND org_id=$2', [id, orgId, email, name, role, externalId])
    await audit({ orgId, action: 'scim.user_updated', targetType: 'user', targetId: id, detail: { email, changes } })
  }
  const wasActive = !cur.disabled_at
  if (wasActive && !active) {
    const sessionsRevoked = await deactivate(orgId, id, false)
    await audit({ orgId, action: 'scim.user_deprovisioned', targetType: 'user', targetId: id, detail: { email, sessionsRevoked, effect: 'Account disabled and signed out everywhere; project data stays with the organization.' } })
  } else if (!wasActive && active) {
    await query('UPDATE users SET disabled_at=NULL, failed_logins=0, locked_until=NULL, scim_modified_at=NOW() WHERE id=$1 AND org_id=$2', [id, orgId])
    await audit({ orgId, action: 'scim.user_reactivated', targetType: 'user', targetId: id, detail: { email } })
  }
  return getScimUser(orgId, id)
}

export async function deleteScimUser(orgId: string, id: string): Promise<void> {
  const cur = await getScimUser(orgId, id)
  if (cur.role === 'owner') throw new ScimError(400, 'Owners are managed in Planora, not through SCIM.', 'mutability')
  const sessionsRevoked = await deactivate(orgId, id, true)
  await audit({ orgId, action: 'scim.user_deleted', targetType: 'user', targetId: id, detail: { email: cur.email, sessionsRevoked, effect: 'Account disabled and signed out everywhere; project data stays with the organization.' } })
}

/* ─── Discovery (RFC 7644 §4) ───────────────────────── */

export function serviceProviderConfig(origin: string) {
  return {
    schemas: [SCHEMA.spc],
    documentationUri: 'https://github.com/Hoshmand-AI/planora/blob/main/docs/security/SECURITY-OVERVIEW.md',
    patch: { supported: true },
    bulk: { supported: false, maxOperations: 0, maxPayloadSize: 0 },
    filter: { supported: true, maxResults: 200 },
    changePassword: { supported: false },
    sort: { supported: false },
    etag: { supported: false },
    authenticationSchemes: [{ type: 'oauthbearertoken', name: 'OAuth Bearer Token', description: 'Organization SCIM token from Organization → SCIM provisioning, sent as Authorization: Bearer scim_…', primary: true }],
    meta: { resourceType: 'ServiceProviderConfig', location: `${scimBase(origin)}/ServiceProviderConfig` },
  }
}

export function userResourceType(origin: string) {
  return {
    schemas: [SCHEMA.resourceType], id: 'User', name: 'User', endpoint: '/Users', description: 'Organization member', schema: SCHEMA.user,
    meta: { resourceType: 'ResourceType', location: `${scimBase(origin)}/ResourceTypes/User` },
  }
}

const attr = (name: string, extra: Record<string, unknown> = {}) => ({
  name, type: 'string', multiValued: false, required: false, caseExact: false, mutability: 'readWrite', returned: 'default', uniqueness: 'none', ...extra,
})

export function userSchema(origin: string) {
  return {
    schemas: [SCHEMA.schema], id: SCHEMA.user, name: 'User', description: 'Organization member',
    attributes: [
      attr('userName', { required: true, uniqueness: 'server', description: 'The member\'s email address (in a verified SSO domain).' }),
      attr('externalId', { caseExact: true }),
      { ...attr('name', { type: 'complex' }), subAttributes: [attr('formatted'), attr('givenName'), attr('familyName')] },
      attr('displayName'),
      attr('active', { type: 'boolean', description: 'false disables the member and ends all their sessions.' }),
      { ...attr('emails', { type: 'complex', multiValued: true }), subAttributes: [attr('value'), attr('type'), attr('primary', { type: 'boolean' })] },
      { ...attr('roles', { type: 'complex', multiValued: true, description: 'admin, scheduler, reviewer or viewer' }), subAttributes: [attr('value', { canonicalValues: ['admin', 'scheduler', 'reviewer', 'viewer'] }), attr('primary', { type: 'boolean' })] },
    ],
    meta: { resourceType: 'Schema', location: `${scimBase(origin)}/Schemas/${SCHEMA.user}` },
  }
}
