import { NextResponse } from 'next/server'
import { api } from '@/lib/server/api'
import { randomUUID as uuid } from 'crypto'
import { createActivities, createRelationships, createSchedule, getSchedules, savePlan, type Activity } from '@/lib/db'
import { profileFrom } from '@/lib/planning/elicitation'
import { publishBlockers } from '@/lib/planning/evaluation'
import { approvalOfCurrentVersion } from '@/lib/server/approval'
import { loadPlanContext, planView } from '../context'

/**
 * Publish the generated schedule as a project schedule so the analyze/monitor stages
 * (dashboard, timeline, Ask AI, quality checks, updates) work on it. Each publish is a new version.
 *
 * Body: { confirm?: boolean }. A plan whose forecast misses its required / contractual date by more
 * than the threshold, or whose project type has no Planora template, is refused with 409
 * `publish_confirmation_required` and the warnings until the caller resends with confirm: true. The
 * confirmation and the warnings it overrode are recorded in the audit trail.
 */
export const POST = api<{ id: string }>({ permission: 'plan.publish' }, async (req, { params, auth }) => {
  const r = await loadPlanContext(req, params.id, auth)
  const { plan, ctx } = r
  const g = plan.generated
  if (!g?.cpm) return NextResponse.json({ error: 'Generate the schedule first.' }, { status: 400 })

  if (ctx.settings.requireApprovalToPublish) {
    // Only an independent approval of exactly this content counts: any edit, override or regeneration
    // after the approval changes the schedule fingerprint and needs a fresh review.
    const state = approvalOfCurrentVersion(plan)
    if (!state.approved) {
      const stale = state.staleApprovals > 0 && !state.rejected
      return NextResponse.json({
        error: stale
          ? 'The schedule changed after it was approved. Your organization requires a fresh approving review of the current version by someone other than its author before it can be published.'
          : 'Your organization requires an approving review of this version by someone other than its author before it can be published.',
        code: 'approval_required',
        ...(stale ? { reason: 'approval_stale' } : {}),
      }, { status: 403 })
    }
  }
  const body = await req.json().catch(() => ({})) as { confirm?: unknown }
  const blockers = publishBlockers(g, plan.answers)
  if (blockers.length && body?.confirm !== true) {
    return NextResponse.json({
      error: `Publishing needs confirmation: ${blockers.map(b => b.text).join(' ')}`,
      code: 'publish_confirmation_required',
      warnings: blockers,
    }, { status: 409 })
  }
  const existing = (await getSchedules(ctx.orgId)).filter(s => s.planId === plan.id)
  const scheduleId = uuid()
  const profile = profileFrom(plan.answers)
  const t = g.cpm.times
  const idMap = new Map(g.activities.map(a => [a.id, `${scheduleId}:${a.id}`]))
  const hasPred = new Set(g.links.map(l => l.to))
  const activities: Activity[] = g.activities.map(a => ({
    id: idMap.get(a.id)!, scheduleId, activityId: a.code, name: a.name, wbs: a.phase,
    duration: a.duration, remainingDuration: a.duration, percentComplete: 0,
    earlyStart: t[a.id]?.earlyStart ?? null, earlyFinish: t[a.id]?.earlyFinish ?? null,
    lateStart: t[a.id]?.lateStart ?? null, lateFinish: t[a.id]?.lateFinish ?? null,
    actualStart: null, actualFinish: null,
    // The published version is the baseline for monitoring.
    baselineStart: t[a.id]?.earlyStart ?? null, baselineFinish: t[a.id]?.earlyFinish ?? null,
    totalFloat: t[a.id]?.totalFloat ?? 0, freeFloat: t[a.id]?.freeFloat ?? 0, isCritical: !!t[a.id]?.critical,
    status: 'not_started', activityType: a.type,
    milestoneKind: a.type === 'milestone' ? (a.milestoneKind ?? (hasPred.has(a.id) ? 'finish' : 'start')) : null,
    calendarId: a.calendarId ?? g.defaultCalendarId, constraintType: a.constraint?.type ?? null, constraintDate: a.constraint?.date ?? null,
    category: a.category, sourceId: a.id,
  }))
  const schedule = await createSchedule({
    id: scheduleId, userId: ctx.userId, orgId: ctx.orgId, name: plan.name, version: `Plan v${existing.length + 1}`,
    sourceType: 'generated', fileName: 'Generated by Planora', uploadedAt: new Date().toISOString(),
    activityCount: activities.length, relationshipCount: g.links.length,
    projectStart: g.projectStart, projectFinish: g.cpm.projectFinish, dataDate: g.projectStart, varianceDays: 0,
    criticalCount: activities.filter(a => a.isCritical).length, percentComplete: 0,
    calendars: g.calendars, defaultCalendarId: g.defaultCalendarId, warnings: [],
    planId: plan.id, projectType: profile.projectType ?? null, region: profile.state ?? null, grossSqft: profile.grossSqft ?? null,
    // The published schedule stays inside the plan's workspace (ethical wall).
    workspaceId: plan.workspaceId ?? null,
  })
  await createActivities(activities)
  await createRelationships(g.links.map(l => ({ id: `${scheduleId}:${l.id}`, scheduleId, predecessorId: idMap.get(l.from)!, successorId: idMap.get(l.to)!, type: l.type, lag: l.lag })))
  plan.scheduleId = scheduleId
  plan.audit.push({ at: new Date().toISOString(), by: ctx.name, action: 'publish', detail: `${schedule.version} (${activities.length} activities)${blockers.length ? `. Published with confirmation despite: ${blockers.map(b => b.code === 'late' ? `forecast ${b.days} days late` : 'no matching template').join('; ')}` : ''}` })
  const saved = await savePlan(plan)
  return NextResponse.json({ ...(await planView(saved, ctx.orgId)), schedule })
})
