import { NextResponse } from 'next/server'
import { api } from '@/lib/server/api'
import { randomUUID as uuid } from 'crypto'
import { createActivities, createRelationships, createSchedule, getSchedules, savePlan, type Activity } from '@/lib/db'
import { profileFrom } from '@/lib/planning/elicitation'
import { loadPlanContext, planView } from '../context'

/**
 * Publish the generated schedule as a project schedule so the analyze/monitor stages
 * (dashboard, timeline, Ask AI, quality checks, updates) work on it. Each publish is a new version.
 */
export const POST = api<{ id: string }>({ permission: 'plan.publish' }, async (req, { params, auth }) => {
  const r = await loadPlanContext(req, params.id, auth)
  const { plan, ctx } = r
  const g = plan.generated
  if (!g?.cpm) return NextResponse.json({ error: 'Generate the schedule first.' }, { status: 400 })

  if (ctx.settings.requireApprovalToPublish) {
    // Only reviews of the current generation count, and the latest one must not be a rejection.
    const current = plan.reviews.filter(rv => rv.generatedAt ? rv.generatedAt === g.generatedAt : rv.at >= g.generatedAt)
    const latest = current[current.length - 1]
    const approved = current.some(rv => rv.verdict !== 'reject' && rv.reviewerUserId && rv.reviewerUserId !== plan.userId)
    if (!approved || latest?.verdict === 'reject') {
      return NextResponse.json({ error: 'Your organization requires an approving review of this version by someone other than its author before it can be published.', code: 'approval_required' }, { status: 403 })
    }
  }
  const existing = (await getSchedules(ctx.orgId)).filter(s => s.planId === plan.id)
  const scheduleId = uuid()
  const profile = profileFrom(plan.answers)
  const t = g.cpm.times
  const idMap = new Map(g.activities.map(a => [a.id, `${scheduleId}:${a.id}`]))
  const activities: Activity[] = g.activities.map(a => ({
    id: idMap.get(a.id)!, scheduleId, activityId: a.code, name: a.name, wbs: a.phase,
    duration: a.duration, remainingDuration: a.duration, percentComplete: 0,
    earlyStart: t[a.id]?.earlyStart ?? null, earlyFinish: t[a.id]?.earlyFinish ?? null,
    lateStart: t[a.id]?.lateStart ?? null, lateFinish: t[a.id]?.lateFinish ?? null,
    actualStart: null, actualFinish: null,
    // The published version is the baseline for monitoring.
    baselineStart: t[a.id]?.earlyStart ?? null, baselineFinish: t[a.id]?.earlyFinish ?? null,
    totalFloat: t[a.id]?.totalFloat ?? 0, freeFloat: t[a.id]?.freeFloat ?? 0, isCritical: !!t[a.id]?.critical,
    status: 'not_started', activityType: a.type,
    calendarId: a.calendarId ?? g.defaultCalendarId, constraintType: a.constraint?.type ?? null, constraintDate: a.constraint?.date ?? null,
    category: a.category, sourceId: a.id,
  }))
  const schedule = await createSchedule({
    id: scheduleId, userId: ctx.userId, orgId: ctx.orgId, name: plan.name, version: `Plan v${existing.length + 1}`,
    sourceType: 'generated', fileName: 'Generated by Planora', uploadedAt: new Date().toISOString(),
    activityCount: activities.length, relationshipCount: g.links.length,
    projectStart: g.projectStart, projectFinish: g.cpm.projectFinish, dataDate: g.projectStart, varianceDays: 0,
    criticalCount: activities.filter(a => a.isCritical).length, percentComplete: 0,
    calendars: g.calendars, defaultCalendarId: g.defaultCalendarId, warnings: [],
    planId: plan.id, projectType: profile.projectType ?? null, region: profile.state ?? null, grossSqft: profile.grossSqft ?? null,
  })
  await createActivities(activities)
  await createRelationships(g.links.map(l => ({ id: `${scheduleId}:${l.id}`, scheduleId, predecessorId: idMap.get(l.from)!, successorId: idMap.get(l.to)!, type: l.type, lag: l.lag })))
  plan.scheduleId = scheduleId
  plan.audit.push({ at: new Date().toISOString(), by: ctx.name, action: 'publish', detail: `${schedule.version} (${activities.length} activities)` })
  const saved = await savePlan(plan)
  return NextResponse.json({ ...(await planView(saved, ctx.orgId)), schedule })
})
